// Constants.js - shared IDs and naming patterns

const PRODUCT_TEMPLATES_FOLDER_ID = "1pILM_aJi8Kp0L8Ue2X04TXlaAli_WBTy";
const DKC_UPLOAD_FOLDER_ID = "1sUjZScAbY63gHxGhbP_SlfUd_RaJEtBv";
const DKC_IMPORTS_FOLDER_ID = "1F_rvK5YUDFGXa7aWcMkmnMSPe8X58fdZ";
const DKC_WORK_FOLDER_ID = "1dKHCsUJPDdvtrRY7Yz8FVCMf3KPB9PrI";

const SCRIPT_PROP_LATEST_TEMPLATE_ID = "LATEST_TEMPLATE_ID";
const TEMPLATE_NAME_PREFIX = "RB-Template-v1-";
const ENGINE_NAME_PREFIX = "RB-";
const ENGINE_NAME_SUFFIX = "-Engine";
